# Generated by Django 5.2.17 on 2026-09-21 08:18

import apps.phrases.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_phrase', models.CharField(max_length=300, verbose_name='orijinal cümle')),
                ('translation', models.CharField(max_length=300, verbose_name='çeviri')),
                ('word_breakdown', models.JSONField(default=list, validators=[apps.phrases.validators.validate_word_breakdown], verbose_name='kelime kelime ses karşılığı')),
                ('association_story', models.TextField(verbose_name='çağrışım hikayesi')),
                ('source', models.CharField(choices=[('manual', 'Manuel'), ('ai_generated', 'AI ile üretildi')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PhraseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('learning', 'Öğreniliyor'), ('learned', 'Öğrenildi')], default='learning', max_length=10)),
                ('swipe_left_count', models.PositiveIntegerField(default=0)),
                ('swipe_right_count', models.PositiveIntegerField(default=0)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('next_review_at', models.DateTimeField(blank=True, null=True)),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='phrases.phrase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrase_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'phrase'), name='unique_progress_per_user_phrase')],
            },
        ),
    ]
