# Generated by Django 5.2.17 on 2026-09-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrases', '0004_spaced_repetition'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigeneration',
            name='target_language',
            field=models.CharField(choices=[('en', 'İngilizce'), ('es', 'İspanyolca')], default='en', max_length=8, verbose_name='hedef dil'),
        ),
        migrations.AddField(
            model_name='phrase',
            name='target_language',
            field=models.CharField(choices=[('en', 'İngilizce'), ('es', 'İspanyolca')], default='en', max_length=8, verbose_name='hedef dil'),
        ),
    ]
