# Generated by Django 5.2.17 on 2026-09-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrases', '0005_multi_language_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='example_sentence',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='örnek cümle'),
        ),
        migrations.AddField(
            model_name='phrase',
            name='example_sentence_translation',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='örnek cümlenin çevirisi'),
        ),
    ]
